openapi: 3.1.0
info:
  version: 1.0.0
  title: hw2-mongodb
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API for a notebook application using MongoDB
tags:
  - name: auth
    description: Operations with user.
  - name: boards
    description: Operations with boards.
servers:
  - url: http://localhost:3000
  - url: https://backend-taskpro.onrender.com
paths:
  /auth/register:
    post:
      $ref: ./swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ./swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ./swagger/paths/auth/logout.yaml
  /auth/refresh:
    post:
      $ref: ./swagger/paths/auth/refresh.yaml
  /auth/user:
    get:
      $ref: ./swagger/paths/auth/getUser.yaml
    patch:
      $ref: ./swagger/paths/auth/patchUser.yaml

  /boards:
    get:
      $ref: ./swagger/paths/boards/get.yaml
    post:
      $ref: ./swagger/paths/boards/post.yaml

  /boards/:boardId:
    get:
      $ref: ./swagger/paths/boards/{boardId}/get.yaml
    patch:
      $ref: ./swagger/paths/boards/{boardId}/patch.yaml
    delete:
      $ref: ./swagger/paths/boards/{boardId}/delete.yaml

 /boards/:boardId/columns:
    get:
      $ref: ./swagger/paths/boards/{boardId}/columns/get.yaml
    post:
      $ref: ./swagger/paths/boards/{boardId}/columns/post.yaml

  /boards/:boardId/columns/:columnId:
    get:
      $ref: ./swagger/paths/boards/{boardId}/columns/{columnId}/get.yaml
    patch:
      $ref: ./swagger/paths/boards/{boardId}/columns/{columnId}/patch.yaml
    delete:
      $ref: ./swagger/paths/boards/{boardId}/columns/{columnId}/delete.yaml

   /boards/:boardId/columns/:columnId/cards:
    get:
      $ref: ./swagger/paths/boards/{boardId}/columns/:columnId/cards/get.yaml
    post:
      $ref: ./swagger/paths/boards/{boardId}/columns/:columnId/cards/post.yaml

   /boards/:boardId/columns/:columnId/cards/:cardId:
    get:
      $ref: ./swagger/paths/boards/{boardId}/columns/{columnId}/:columnId/cards/get.yaml
    patch:
      $ref: ./swagger/paths/boards/{boardId}/columns/{columnId}/patch.yaml
    delete:
      $ref: ./swagger/paths/boards/{boardId}/columns/{columnId}/delete.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
