openapi: 3.1.0
info:
  version: 1.0.0
  title: hw2-mongodb
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API for a notebook application using MongoDB

tags:
  - name: auth
    description: Operations with user.
  - name: boards
    description: Operations with boards.
  - name: columns
    description: Operations with columns.
  - name: cards
    description: Operations with cards.
  - name: need-help
    description: Feedback from user.

servers:
  - url: https://backend-taskpro.onrender.com
  - url: http://localhost:3000

paths:
  /auth/register:
    post:
      $ref: ./swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ./swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ./swagger/paths/auth/logout.yaml
  /auth/refresh:
    post:
      $ref: ./swagger/paths/auth/refresh.yaml
  /auth/user:
    get:
      $ref: ./swagger/paths/auth/getUser.yaml
    patch:
      $ref: ./swagger/paths/auth/patchUser.yaml
  /boards:
    get:
      $ref: ./swagger/paths/boards/get.yaml
    post:
      $ref: ./swagger/paths/boards/post.yaml
  /boards/{boardId}:
    get:
      $ref: ./swagger/paths/boards/{boardId}/get.yaml
    patch:
      $ref: ./swagger/paths/boards/{boardId}/patch.yaml
    delete:
      $ref: ./swagger/paths/boards/{boardId}/delete.yaml
  /columns/{boardId}:
    get:
      $ref: ./swagger/paths/columns/{boardId}/get.yaml
    post:
      $ref: ./swagger/paths/columns/{boardId}/post.yaml

  /columns/v1/{columnId}:
    get:
      $ref: ./swagger/paths/columns/v1/{columnId}/get.yaml
    patch:
      $ref: ./swagger/paths/columns/v1/{columnId}/patch.yaml
    delete:
      $ref: ./swagger/paths/columns/v1/{columnId}/delete.yaml
  /cards/{columnId}:
    get:
      $ref: ./swagger/paths/cards/{columnId}/get.yaml
    post:
      $ref: ./swagger/paths/cards/{columnId}/post.yaml
  /cards/v1/{cardId}:
    get:
      $ref: ./swagger/paths/cards/v1/{cardId}/get.yaml
    patch:
      $ref: ./swagger/paths/cards/v1/{cardId}/patch.yaml
    delete:
      $ref: ./swagger/paths/cards/v1/{cardId}/delete.yaml
  /need-help:
    post:
      $ref: ./swagger/paths/needHelp/post.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
